/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.BeansLivro;
import modeloBeans.ModeloTabela;
import modeloConnection.ConexaoBD;
import modeloDao.DaoLivros;

/**
 *
 * @author yuril
 */
public class FormPesquisarEditar extends javax.swing.JFrame {

    BeansLivro mod = new BeansLivro();
    DaoLivros control = new DaoLivros();
    ConexaoBD con = new ConexaoBD();

    /**
     * Creates new form FormPesquisar
     */
    public FormPesquisarEditar() {
        initComponents();

        setIcon();

        jTextFieldCodLivro.setVisible(false);
        jTextFieldPesquisaExport.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPesquisarEditar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonEditar = new javax.swing.JButton();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLivros = new javax.swing.JTable();
        jButtonExcluir = new javax.swing.JButton();
        jTextFieldPesquisaExport = new javax.swing.JTextField();
        jTextFieldCodLivro = new javax.swing.JTextField();
        jComboBoxTipoPesquisa = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisar/Editar Livros");

        jLabelPesquisarEditar.setFont(new java.awt.Font("BankGothic Lt BT", 1, 24)); // NOI18N
        jLabelPesquisarEditar.setText("Pesquisar/Editar Livros");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jTextFieldPesquisa.setToolTipText("");
        jTextFieldPesquisa.setName(""); // NOI18N

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jTableLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableLivros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLivrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableLivros);

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jComboBoxTipoPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Título", "Autor", "Editora", "Formato", "Box", "Lido", "Sequência" }));

        jLabel1.setText("Pesquisar por:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jTextFieldCodLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jTextFieldPesquisaExport, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxTipoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPesquisar)
                .addGap(145, 145, 145))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisar)
                    .addComponent(jComboBoxTipoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonEditar)
                        .addGap(57, 57, 57)
                        .addComponent(jButtonExcluir)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPesquisaExport, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jTextFieldCodLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jTextFieldPesquisa.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelPesquisarEditar)
                .addGap(301, 301, 301))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelPesquisarEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(981, 631));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        FormEditarLivro tela = new FormEditarLivro();
        tela.exportaPesquisa(this, jTextFieldPesquisaExport.getText());
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        mod.setPesquisa(jTextFieldPesquisa.getText());
        BeansLivro model = control.buscaLivro(mod);
        //jLabelCodLivro.setText(String.valueOf(model.getCod()));
        //jTextFieldPesquisaExport.setText(model.getTitulo());
        //preencherTabelaPlus("select *from livros order by cod_livro", jTextFieldPesquisa.getText());
        if (jComboBoxTipoPesquisa.getSelectedItem().equals("Título")) {
            preencherTabela("select *from livros where titulo_livro like'%" + mod.getPesquisa() + "%' order by cod_livro");
        } else if (jComboBoxTipoPesquisa.getSelectedItem().equals("Autor")) {
            preencherTabela("select *from livros where autor_livro like'%" + mod.getPesquisa() + "%' order by cod_livro");
        } else if (jComboBoxTipoPesquisa.getSelectedItem().equals("Editora")) {
            preencherTabela("select *from livros where editora_livro like'%" + mod.getPesquisa() + "%' order by cod_livro");
        } else if (jComboBoxTipoPesquisa.getSelectedItem().equals("Formato")) {
            preencherTabela("select *from livros where formato_livro like'" + mod.getPesquisa() + "%' order by cod_livro");
        } else if (jComboBoxTipoPesquisa.getSelectedItem().equals("Box")) {
            preencherTabela("select *from livros where box_livro like'" + mod.getPesquisa() + "%' order by cod_livro");
        } else if (jComboBoxTipoPesquisa.getSelectedItem().equals("Lido")) {
            preencherTabela("select *from livros where lido_livro like'" + mod.getPesquisa() + "%' order by cod_livro");
        } else if (jComboBoxTipoPesquisa.getSelectedItem().equals("Sequência")) {
            preencherTabela("select *from livros where sequencia_livro like'%" + mod.getPesquisa() + "%' order by cod_livro");
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int resposta;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir o livro?");
        if (resposta == JOptionPane.YES_OPTION) {
            mod.setCod(Integer.parseInt(jTextFieldCodLivro.getText()));
            control.excluir(mod);
            preencherTabela("select *from livros where titulo_livro like'%" + mod.getPesquisa() + "%' order by cod_livro");
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTableLivrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLivrosMouseClicked
        String titulo_livro = "" + jTableLivros.getValueAt(jTableLivros.getSelectedRow(), 1);
        con.conexao();

        con.executaSql("select *from livros where titulo_livro='" + titulo_livro + "'");
        try {
            con.rs.first();
            jTextFieldCodLivro.setText(String.valueOf(con.rs.getInt("cod_livro")));
            jTextFieldPesquisaExport.setText(con.rs.getString("titulo_livro"));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar dados." + ex);
        }

        con.desconecta();
    }//GEN-LAST:event_jTableLivrosMouseClicked

    public void preencherTabela(String Sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Cod", "Título", "Autor", "Editora", "Páginas", "Formato", "Box", "Lido", "Sequencia", "Volume"};
        con.conexao();

        con.executaSql(Sql);
        try {
            con.rs.first();
            do {
                dados.add(new Object[]{con.rs.getInt("cod_livro"), //1
                    con.rs.getString("titulo_livro"), //2
                    con.rs.getString("autor_livro"),//3
                    con.rs.getString("editora_livro"), //4
                    con.rs.getInt("paginas_livro"), //5
                    con.rs.getString("formato_livro"),//6
                    con.rs.getString("box_livro"),//7
                    con.rs.getString("lido_livro"), //8
                    con.rs.getString("sequencia_livro"),//9
                    con.rs.getInt("numseq_livro")});//10
            } while (con.rs.next());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Livro Não encontrado! Pesquise novamente.");
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTableLivros.setModel(modelo);
        jTableLivros.getColumnModel().getColumn(0).setPreferredWidth(40);
        jTableLivros.getColumnModel().getColumn(1).setPreferredWidth(300);
        jTableLivros.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTableLivros.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTableLivros.getColumnModel().getColumn(4).setPreferredWidth(80);
        jTableLivros.getColumnModel().getColumn(5).setPreferredWidth(80);
        jTableLivros.getColumnModel().getColumn(6).setPreferredWidth(80);
        jTableLivros.getColumnModel().getColumn(7).setPreferredWidth(60);
        jTableLivros.getColumnModel().getColumn(8).setPreferredWidth(150);
        jTableLivros.getColumnModel().getColumn(9).setPreferredWidth(60);
        jTableLivros.setAutoResizeMode(jTableLivros.AUTO_RESIZE_OFF);
        jTableLivros.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        con.desconecta();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPesquisarEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPesquisarEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPesquisarEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPesquisarEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPesquisarEditar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JComboBox<String> jComboBoxTipoPesquisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelPesquisarEditar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLivros;
    private javax.swing.JTextField jTextFieldCodLivro;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jTextFieldPesquisaExport;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        URL caminhoIcone = getClass().getResource("/imagens/Book.png");
        Image iconePrograma = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconePrograma);
    }
}
