/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JOptionPane;
import modeloBeans.BeansLivro;
import modeloConnection.ConexaoBD;
import modeloDao.DaoLivros;

/**
 *
 * @author yuril
 */
public class FormEditarLivro extends javax.swing.JFrame {

    BeansLivro mod = new BeansLivro();
    DaoLivros control = new DaoLivros();
    ConexaoBD con = new ConexaoBD();
    private String pesquisa;
    private boolean check = false;
    private boolean checkBox = false;

    public void exportaPesquisa(FormPesquisarEditar model, String search) {
        jTextFieldPesquisaEditar.setText(search);
        //jLabelPesquisa.setVisible(false);

        con.conexao();

        //con.executaSql("select *from livros where titulo_livro like'%" + String.valueOf(jTextFieldPesquisaEditar.getText()) + "%'");
        con.executaSql("select *from livros where titulo_livro='" + jTextFieldPesquisaEditar.getText() + "'");
        //con.executaSql("select *from livros where titulo_livro like'" + jTextFieldPesquisa.getText() + "'");
        //con.executaSql("select *from livros order by cod_livro");

        try {
            con.rs.first();
            jTextFieldCodLivro.setText(String.valueOf(con.rs.getInt("cod_livro")));
            jTextFieldTitulo.setText(con.rs.getString("titulo_Livro"));
            jTextFieldAutor.setText(con.rs.getString("autor_livro"));
            jTextFieldEditora.setText(con.rs.getString("editora_livro"));
            jTextFieldPaginas.setText(String.valueOf(con.rs.getInt("paginas_livro")));
            jComboBoxFormato.setSelectedItem(con.rs.getString("formato_livro"));
            if ("Sim".equals(con.rs.getString("box_livro"))) {
                jCheckBoxBoxEditar.setSelected(true);
            } else {
                if (con.rs.getString("formato_livro").equals("Físico")) {
                    jCheckBoxBoxEditar.setEnabled(true);
                    jCheckBoxBoxEditar.setSelected(false);
                } else {
                    jCheckBoxBoxEditar.setEnabled(false);
                }
            }
            jComboBoxLido.setSelectedItem(con.rs.getString("lido_livro"));
            if (!"".equals(con.rs.getString("sequencia_livro"))) {
                jCheckBoxSeq.setSelected(true);
                jTextFieldSequencia.setText(con.rs.getString("sequencia_livro"));
                jTextFieldNumSequencia.setText(String.valueOf(con.rs.getInt("numseq_livro")));
                check = true;
            } else {
                jCheckBoxSeq.setSelected(false);
                jTextFieldSequencia.setEnabled(false);
                jTextFieldNumSequencia.setEnabled(false);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Selecione um Livro na Tabela.");
        }

        con.desconecta();
    }

    public String getPesquisa() {
        return pesquisa;
    }

    public void setPesquisa(String pesquisa) {
        this.pesquisa = pesquisa;
    }

    public void preencherCampos() {

    }

    /**
     * Creates new form FormLivro
     */
    public FormEditarLivro() {
        initComponents();

        getIcon();

        jTextFieldCodLivro.setVisible(false);
        jTextFieldPesquisaEditar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxSequencia = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jTextFieldAutor = new javax.swing.JTextField();
        jTextFieldSequencia = new javax.swing.JTextField();
        jTextFieldEditora = new javax.swing.JTextField();
        jTextFieldPaginas = new javax.swing.JTextField();
        jComboBoxFormato = new javax.swing.JComboBox<>();
        jComboBoxLido = new javax.swing.JComboBox<>();
        jTextFieldNumSequencia = new javax.swing.JTextField();
        jCheckBoxSeq = new javax.swing.JCheckBox();
        jCheckBoxBoxEditar = new javax.swing.JCheckBox();
        jLabelCadastroLivros = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jTextFieldPesquisaEditar = new javax.swing.JTextField();
        jTextFieldCodLivro = new javax.swing.JTextField();

        jCheckBoxSequencia.setText("Sequencia:");
        jCheckBoxSequencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSequenciaActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar Livro");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Título:");

        jLabel2.setText("Autor:");

        jLabel3.setText("Editora:");

        jLabel4.setText("Páginas:");

        jLabel5.setText("Formato:");

        jLabel6.setText("Lido:");

        jLabel8.setText("Volume:");

        jComboBoxFormato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Físico", "Digital" }));
        jComboBoxFormato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFormatoActionPerformed(evt);
            }
        });

        jComboBoxLido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));

        jCheckBoxSeq.setText("Sequencia:");
        jCheckBoxSeq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSeqActionPerformed(evt);
            }
        });

        jCheckBoxBoxEditar.setText("Box");
        jCheckBoxBoxEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxBoxEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxLido, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldAutor)
                                    .addComponent(jTextFieldTitulo))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jComboBoxFormato, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jCheckBoxBoxEditar)))
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel8)
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jCheckBoxSeq)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNumSequencia, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSequencia, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxFormato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxBoxEditar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxLido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSequencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxSeq))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldNumSequencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabelCadastroLivros.setFont(new java.awt.Font("BankGothic Lt BT", 1, 18)); // NOI18N
        jLabelCadastroLivros.setText("Editar Livro");

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jTextFieldCodLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jTextFieldPesquisaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSalvar)
                .addGap(18, 18, 18)
                .addComponent(jButtonCancelar)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabelCadastroLivros)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelCadastroLivros)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonCancelar)
                    .addComponent(jTextFieldCodLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPesquisaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(510, 529));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxSequenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSequenciaActionPerformed
        //Erro
    }//GEN-LAST:event_jCheckBoxSequenciaActionPerformed

    private void jCheckBoxSeqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSeqActionPerformed
        if (jCheckBoxSeq.isSelected()) {
            check = true;
            jTextFieldSequencia.setEnabled(true);
            jTextFieldNumSequencia.setEnabled(true);
        } else {
            check = false;
            jTextFieldSequencia.setEnabled(false);
            jTextFieldNumSequencia.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBoxSeqActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if (jTextFieldTitulo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite o Título.");
            jTextFieldTitulo.requestFocus();
        } else if (jTextFieldAutor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite o Autor.");
            jTextFieldAutor.requestFocus();
        } else if (jTextFieldEditora.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite a Editora.");
            jTextFieldEditora.requestFocus();
        } else if (jTextFieldPaginas.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite a quantidade de Páginas.");
            jTextFieldPaginas.requestFocus();
        } else if ((jTextFieldSequencia.getText().isEmpty()) && check) {
            if (check == true) {
                JOptionPane.showMessageDialog(null, "Digite o nome da Sequência.");
                jTextFieldSequencia.requestFocus();
            } else {
                mod.setSequencia("");
            }
        } else if ((jTextFieldNumSequencia.getText().isEmpty()) && check) {
            if (check == true) {
                JOptionPane.showMessageDialog(null, "Digite o número da Sequência.");
                jTextFieldNumSequencia.requestFocus();
            } else {
                mod.setNumerosequencia(0);
            }
        } else {
            mod.setCod(Integer.parseInt(jTextFieldCodLivro.getText()));
            mod.setTitulo(jTextFieldTitulo.getText());
            mod.setAutor(jTextFieldAutor.getText());
            mod.setEditora(jTextFieldEditora.getText());
            mod.setPaginas(Integer.parseInt(jTextFieldPaginas.getText()));
            mod.setFormato((String) jComboBoxFormato.getSelectedItem());
            if (checkBox) {
                //if(jComboBoxFormato.getSelectedItem().equals(""));
                mod.setBox("Sim");
            } else {
                mod.setBox("Não");
            }
            mod.setLido((String) jComboBoxLido.getSelectedItem());
            if (check == true) {
                mod.setSequencia(jTextFieldSequencia.getText());
                mod.setNumerosequencia(Integer.parseInt(jTextFieldNumSequencia.getText()));
            } else {
                mod.setSequencia("");
                mod.setNumerosequencia(0);
            }
            control.editar(mod);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jCheckBoxBoxEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxBoxEditarActionPerformed
        checkBox = jCheckBoxBoxEditar.isSelected();
    }//GEN-LAST:event_jCheckBoxBoxEditarActionPerformed

    private void jComboBoxFormatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFormatoActionPerformed
        if (jComboBoxFormato.getSelectedItem() == "Físico") {
            jCheckBoxBoxEditar.setEnabled(true);
        } else {
            jCheckBoxBoxEditar.setEnabled(false);
            jCheckBoxBoxEditar.setSelected(false);
            checkBox = false;
        }
    }//GEN-LAST:event_jComboBoxFormatoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEditarLivro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEditarLivro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEditarLivro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEditarLivro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEditarLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JCheckBox jCheckBoxBoxEditar;
    private javax.swing.JCheckBox jCheckBoxSeq;
    private javax.swing.JCheckBox jCheckBoxSequencia;
    private javax.swing.JComboBox<String> jComboBoxFormato;
    private javax.swing.JComboBox<String> jComboBoxLido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelCadastroLivros;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldAutor;
    private javax.swing.JTextField jTextFieldCodLivro;
    private javax.swing.JTextField jTextFieldEditora;
    private javax.swing.JTextField jTextFieldNumSequencia;
    private javax.swing.JTextField jTextFieldPaginas;
    private javax.swing.JTextField jTextFieldPesquisaEditar;
    private javax.swing.JTextField jTextFieldSequencia;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables

    private void getIcon() {
        URL caminhoIcone = getClass().getResource("/imagens/Book.png");
        Image iconePrograma = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconePrograma);
    }
}
